version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: doae_db
    environment:
      POSTGRES_USER: doae
      POSTGRES_PASSWORD: doae123
      POSTGRES_DB: doae
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - doae_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: doae_pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - doae_network
    restart: always

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: doae_backend
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://doae:doae123@postgres:5432/doae
    ports:
      - "4000:4000"
    networks:
      - doae_network
    volumes:
      - ../apps/backend:/app

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: doae_frontend
    ports:
      - "3000:3000"
    networks:
      - doae_network
    volumes:
      - ../apps/frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

networks:
  doae_network:
    driver: bridge

volumes:
  postgres_data:
